// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10112022_Soechi.Data;

#nullable disable

namespace _10112022Soechi.Migrations
{
    [DbContext(typeof(SoechiContext))]
    [Migration("20221110061339_soechi1")]
    partial class soechi1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_10112022_Soechi.Models.UomModel", b =>
                {
                    b.Property<long>("UOMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UOMID"));

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UOMName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UOMRate")
                        .HasColumnType("int");

                    b.HasKey("UOMID");

                    b.ToTable("UOM");
                });
#pragma warning restore 612, 618
        }
    }
}
